### ISSUE TITLE
Is a separate method really needed here?

### ISSUE THREAD

**Issue by devinrader** [TwilioDevEd/browser-calls-csharp#2]
Is a separate method really needed here?

https://github.com/TwilioDevEd/browser-calls-csharp/blob/master/BrowserCalls.Web/Controllers/CallController.cs#L26

**Comment by acamino** [comment]
This one is more a matter of preference, I like the way how `BuildResponse` hides the **how** of creating the actual response, so that in the _action method_ I just need to specify **what** I need, for instance, _build a response_.

Nonetheless, if you think that `BuildResponse` adds some layer of indirection, I can remove it.

I'd like to know what is your opinion on this one.

**Comment by devinrader** [comment]
@atbaker what do you think?  Not sure the level of abstraction you want here.  I'd tend to agree with @acamino if we needed like 50 lines of code to generate the response, but in this case its like 6.  If this were me writing this app, I'd be OK not having the extra indirection here.

**Comment by atbaker** [comment]
This is definitely a balance.

But for a relatively simple TwiML response like this, I think we should not use the separate method and keep it all in one method.

(I definitely appreciate this kind of good engineering thinking, though, @acamino!)

**Comment by acamino** [comment]
Thanks guys, #9 will resolve this one :grin:
